name: Create Release

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Git with PAT for authentication
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Tag
        run: git tag v1.0.0  # Replace with your desired tag name

      - name: Push Tag
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push --tags

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Replace with the tag you created
          release_name: Release v1.0.0  # Replace with your desired release name
          body: |
            Release notes for v1.0.0
            - Feature 1 implemented
            - Bug fixes
