name: Create Release

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # You may need additional setup steps depending on your project's needs

      - name: Create Tag
        run: git tag v1.0.0  # Replace with your desired tag name

      - name: Push Tag
        run: git push --tags

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Replace with the tag you created
          release_name: Release v1.0.0  # Replace with your desired release name
          body: |
            Release notes for v1.0.0
            - Feature 1 implemented
            - Bug fixes

